/**
 * Bundled tone assets, keyed by {@link ToneId}.
 *
 * Split out of `./feedback` for one reason: `require()` of a `.wav` is a
 * Metro-only transform, so a module containing it cannot be imported from a
 * vitest node test. Keeping the requires here lets `./feedback-signatures`
 * (the mapping under test) stay pure.
 *
 * The WAVs are generated by `scripts/generate-feedback-tones.mjs` — see that
 * file for the tone design (distinct fundamental AND distinct rhythm per
 * outcome, per FR-002).
 */
import type { ToneId } from "./feedback-signatures";

/** Opaque Metro asset module id. */
export type ToneAsset = number;

export const TONE_ASSETS: Record<ToneId, ToneAsset> = {
  /* eslint-disable @typescript-eslint/no-require-imports */
  valid: require("../../assets/audio/valid.wav") as ToneAsset,
  already_scanned:
    require("../../assets/audio/already_scanned.wav") as ToneAsset,
  wrong_event: require("../../assets/audio/wrong_event.wav") as ToneAsset,
  rejected: require("../../assets/audio/rejected.wav") as ToneAsset,
  /* eslint-enable @typescript-eslint/no-require-imports */
};
