import type { PrismaClient } from "@prisma/client";
import { DEMO_IDS } from "./ids.js";

/**
 * Featured event slugs to highlight in the FeaturedHeroCarousel.
 * One per category group — these slugs are generated by the loop in
 * buildEventFixtures() as `${regionCode}-${slugify(title)}`.
 */
const FEATURED_EVENT_SLUGS = [
  "ca-sf-north-beach-jazz-night", // music / nightlife group
  "ca-sf-mission-district-film-screening", // film
  "tx-aus-south-congress-art-pop-up", // arts
  "tx-aus-sixth-street-comedy-night", // open-mics
] as const;

/**
 * Upsert FeaturedItem records for the home-page hero carousel.
 *
 * @param prisma    - PrismaClient instance
 * @param eventSlugToIdMap - map of event slug → event id (from the seeded events)
 */
export const ensureFeaturedItems = async (
  prisma: PrismaClient,
  eventSlugToIdMap: Record<string, string>,
): Promise<void> => {
  const entries = FEATURED_EVENT_SLUGS.map((slug, i) => ({
    slug,
    sortOrder: i,
  }));

  for (const { slug, sortOrder } of entries) {
    const eventId = eventSlugToIdMap[slug];
    if (!eventId) {
      console.warn(
        `[featured-items] Skipping "${slug}" — event not found in map`,
      );
      continue;
    }

    await prisma.featuredItem.upsert({
      where: { itemType_itemId: { itemType: "EVENT", itemId: eventId } },
      update: {
        sortOrder,
        active: true,
        ctaUrl: null,
        curatedByHumanId: DEMO_IDS.human,
      },
      create: {
        itemType: "EVENT",
        itemId: eventId,
        sortOrder,
        active: true,
        ctaUrl: null,
        curatedByHumanId: DEMO_IDS.human,
        curatedAt: new Date(),
      },
    });
    console.log(
      `  [featured-items] Upserted FeaturedItem for "${slug}" (sortOrder=${sortOrder})`,
    );
  }
};

export { FEATURED_EVENT_SLUGS };
